---
driver                    :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false
    privileged            : true
    require_chef_omnibus  : false

provisioner:
    name                  : ansible_push
    verbose               : "vvvv"
    chef_bootstrap_url    : nil
    ansible_config        : "test/ansible.cfg"
    idempotency_test      : True
    diff                  : True

verifier:
  name: serverspec
  remote_exec             : false
  default_pattern         : true

platforms:
 - name                   : ubuntu1404
   driver_config          :
     image                : ubuntu:trusty
     platform             : ubuntu

 - name                   : ubuntu1604
   driver_config          :
     image                : ubuntu:xenial
     platform             : ubuntu
     provision_command:
       - apt-get install -y python-minimal

 - name                   : centos7
   driver_config          :
    image                 : centos:7
    platform              : centos

suites                    :
  - name                  : simple-tests
    provisioner           :
      playbook            : "test/integration/simple-tests/play.yml"
      ansible_playbook_bin: "$(avm path v2.2)ansible-playbook"
